"""Local, deterministic trailer assembly from storyboard images or Veo clips.

Veo is intentionally outside this module.  Keeping the renderer local makes
the no-quota fallback real and lets the dashboard always show an MP4 when
storyboard assets are available.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import subprocess
from typing import Callable, Iterable


TRAILER_CLIP_SECONDS = 8


class TrailerRenderError(RuntimeError):
    """Raised when ffmpeg cannot produce the requested local trailer."""


@dataclass
class TrailerShot:
    scene_id: str
    media_path: Path
    media_kind: str  # "image" or "video"
    caption_words: tuple[str, ...] = field(default_factory=tuple)
    caption_rendered: bool = False


def select_timeline_shots(shots: list[dict], limit: int = 3) -> list[dict]:
    """Select first / middle / last available storyboard shots in timeline order."""
    if limit < 1 or not shots:
        return []
    if len(shots) <= limit:
        return list(shots)

    indices = [round(index * (len(shots) - 1) / (limit - 1)) for index in range(limit)]
    return [shots[index] for index in dict.fromkeys(indices)]


def _ffmpeg_filter(caption_words: tuple[str, ...], text_dir: Path, clip_index: int) -> str:
    """Create drawtext filters with one word visible during each second."""
    filters = ["scale=1280:720:force_original_aspect_ratio=decrease", "pad=1280:720:(ow-iw)/2:(oh-ih)/2"]
    for word_index, word in enumerate(caption_words[:TRAILER_CLIP_SECONDS]):
        caption_file = text_dir / f"caption_{clip_index}_{word_index}.txt"
        caption_file.write_text(word, encoding="utf-8")
        # The work directory is generated by tempfile, so this path has no user input.
        path = str(caption_file).replace("\\", "\\\\").replace(":", "\\:")
        filters.append(
            "drawtext="
            f"textfile='{path}':fontcolor=white:fontsize=52:box=1:boxcolor=black@0.55:"
            "boxborderw=14:x=(w-text_w)/2:y=h-(text_h*2):"
            f"enable='between(t,{word_index},{word_index + 1})'"
        )
    return ",".join(filters)


def _run(command: list[str], runner: Callable[..., subprocess.CompletedProcess] = subprocess.run) -> None:
    try:
        runner(command, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or str(exc)
        raise TrailerRenderError(f"ffmpeg failed: {detail}") from exc


def render_trailer(
    shots: Iterable[TrailerShot],
    output_path: Path,
    music_path: Path | None = None,
    *,
    runner: Callable[..., subprocess.CompletedProcess] = subprocess.run,
) -> Path:
    """Render captioned 16:9 clips, remove Veo native audio, then concatenate them."""
    selected = list(shots)
    if not selected:
        raise TrailerRenderError("at least one storyboard shot is required")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    work_dir = output_path.parent
    text_dir = work_dir / "captions"
    text_dir.mkdir(exist_ok=True)
    rendered: list[Path] = []

    for index, shot in enumerate(selected):
        clip_path = work_dir / f"clip_{index}.mp4"
        command = ["ffmpeg", "-y"]
        if shot.media_kind == "image":
            command.extend(["-loop", "1", "-i", str(shot.media_path), "-t", str(TRAILER_CLIP_SECONDS)])
        elif shot.media_kind == "video":
            command.extend(["-i", str(shot.media_path), "-t", str(TRAILER_CLIP_SECONDS)])
        else:
            raise TrailerRenderError(f"unsupported trailer media kind: {shot.media_kind}")

        command.extend([
            "-vf", _ffmpeg_filter(shot.caption_words, text_dir, index),
            "-r", "24", "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p", str(clip_path),
        ])
        try:
            _run(command, runner)
            shot.caption_rendered = bool(shot.caption_words)
        except TrailerRenderError as exc:
            # Some local ffmpeg builds omit drawtext. Rendering the storyboard
            # trailer is still useful, so retry without captions and leave an
            # explicit false value for the agent metadata.
            if not shot.caption_words or "drawtext" not in str(exc).lower():
                raise
            filter_index = command.index("-vf") + 1
            command[filter_index] = _ffmpeg_filter((), text_dir, index)
            _run(command, runner)
            shot.caption_rendered = False
        rendered.append(clip_path)

    concat_file = work_dir / "clips.txt"
    concat_file.write_text("".join(f"file '{path}'\n" for path in rendered), encoding="utf-8")
    command = ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(concat_file)]
    if music_path:
        # Only the existing Lyria cue is mixed. Each visual clip was rendered with -an.
        command.extend(["-stream_loop", "-1", "-i", str(music_path), "-map", "0:v:0", "-map", "1:a:0", "-shortest", "-c:v", "copy", "-c:a", "aac"])
    else:
        command.extend(["-map", "0:v:0", "-c:v", "copy"])
    command.append(str(output_path))
    _run(command, runner)
    return output_path
